name: Python Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock" # Best for speed, or pyproject.toml

      - name: Set up Python
        run: uv python install 3.10

      - name: Install Dependencies
        # This command reads your pyproject.toml and syncs the environment
        run: uv sync

      - name: Run Pytest
        # uv run ensures the tests use the virtual environment created by sync
        run: uv run pytest tests/