# @package _global_
defaults:
  - _self_
  - model: diag_sheaf
  - dataset: dblp
  - trainer: trainer
  - logger: wandb
  - callbacks: sheaf_nc
  - experiment: null

#tags:
#  - GNN
#  - sheaf
#  - node_classification
sheaf_learner: 'local_concat'
tags: [ GNN, sheaf, node_classification, exp1_1, test ]

dataset:
  homogeneous: true

callbacks:
  early_stopping:
    monitor: 'valid/loss'
  model_checkpoint:
    dirpath: checkpoints/sheafnc_checkpoints/
    monitor: valid/accuracy
    mode: max
    save_top_k: 1

trainer:
  log_every_n_steps: 1

optimization:
  learning_rate: 0.001
  weight_decay: 0.0005
