# IEEE39 dataset configuration
_target_: polynsd.datasets.graph_classification.IEEE39DataModule

root: ../../datasets/ieee39/raw
num_workers: 4
node_feature_type: constant

train_split: 0.8
val_split: 0.1
test_split: 0.1

task: "multiclass"
