#!/bin/sh

/home/jel90/.conda/envs/polysheaf/bin/python -u -m exp.run \
    --dataset=all_grids_node \
    --task=regression \
    --d=3 \
    --layers=10 \
    --hidden_channels=40 \
    --left_weights=True \
    --right_weights=True \
    --lr=0.00001 \
    --maps_lr=0.00001 \
    --input_dropout=0.0 \
    --dropout=0.2 \
    --use_act=True \
    --model=DiagSheafPolynomial \
    --polynomial_type="ChebyshevType1" \
    --normalised=True \
    --deg_normalised=False \
    --lambda_max_choice="iterative" \
    --chebyshev_layers_K=15 \
    --early_stopping=1000 \
    --weight_decay=0.005 \
    --folds=1 \
    --epochs=50 \
    --sparse_learner=False \
    --snapshot_train_samples_per_epoch=500 \
    --snapshot_eval_samples=500 \
    --cuda=0 \
    --entity="jelloyd22-university-of-cambridge" \
    --wandb_project="powergrids_node"